# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll", "~> 4.2"
gem "jekyll-theme-primer", "~> 0.4"
gem "jekyll-theme-cayman", "~> 0.2"
gem "webrick"