export const TEST_REPO = {
  id: 41881900,
  name: 'vscode',
  full_name: 'microsoft/vscode',
  private: false,
  owner: Object,
  html_url: 'https://github.com/microsoft/vscode',
  description: 'Visual Studio Code',
  fork: false,
  url: 'https://api.github.com/repos/microsoft/vscode',
  forks_url: 'https://api.github.com/repos/microsoft/vscode/forks',
  keys_url: 'https://api.github.com/repos/microsoft/vscode/keys{/key_id}',
  collaborators_url:
    'https://api.github.com/repos/microsoft/vscode/collaborators{/collaborator}',
  teams_url: 'https://api.github.com/repos/microsoft/vscode/teams',
  hooks_url: 'https://api.github.com/repos/microsoft/vscode/hooks',
  issue_events_url:
    'https://api.github.com/repos/microsoft/vscode/issues/events{/number}',
  events_url: 'https://api.github.com/repos/microsoft/vscode/events',
  assignees_url:
    'https://api.github.com/repos/microsoft/vscode/assignees{/user}',
  branches_url:
    'https://api.github.com/repos/microsoft/vscode/branches{/branch}',
  tags_url: 'https://api.github.com/repos/microsoft/vscode/tags',
  blobs_url: 'https://api.github.com/repos/microsoft/vscode/git/blobs{/sha}',
  git_tags_url: 'https://api.github.com/repos/microsoft/vscode/git/tags{/sha}',
  git_refs_url: 'https://api.github.com/repos/microsoft/vscode/git/refs{/sha}',
  trees_url: 'https://api.github.com/repos/microsoft/vscode/git/trees{/sha}',
  statuses_url: 'https://api.github.com/repos/microsoft/vscode/statuses/{sha}',
  languages_url: 'https://api.github.com/repos/microsoft/vscode/languages',
  stargazers_url: 'https://api.github.com/repos/microsoft/vscode/stargazers',
  contributors_url:
    'https://api.github.com/repos/microsoft/vscode/contributors',
  subscribers_url: 'https://api.github.com/repos/microsoft/vscode/subscribers',
  subscription_url:
    'https://api.github.com/repos/microsoft/vscode/subscription',
  commits_url: 'https://api.github.com/repos/microsoft/vscode/commits{/sha}',
  git_commits_url:
    'https://api.github.com/repos/microsoft/vscode/git/commits{/sha}',
  comments_url:
    'https://api.github.com/repos/microsoft/vscode/comments{/number}',
  issue_comment_url:
    'https://api.github.com/repos/microsoft/vscode/issues/comments{/number}',
  contents_url:
    'https://api.github.com/repos/microsoft/vscode/contents/{+path}',
  compare_url:
    'https://api.github.com/repos/microsoft/vscode/compare/{base}...{head}',
  merges_url: 'https://api.github.com/repos/microsoft/vscode/merges',
  archive_url:
    'https://api.github.com/repos/microsoft/vscode/{archive_format}{/ref}',
  downloads_url: 'https://api.github.com/repos/microsoft/vscode/downloads',
  issues_url: 'https://api.github.com/repos/microsoft/vscode/issues{/number}',
  pulls_url: 'https://api.github.com/repos/microsoft/vscode/pulls{/number}',
  milestones_url:
    'https://api.github.com/repos/microsoft/vscode/milestones{/number}',
  notifications_url:
    'https://api.github.com/repos/microsoft/vscode/notifications{?since,all,participating}',
  labels_url: 'https://api.github.com/repos/microsoft/vscode/labels{/name}',
  releases_url: 'https://api.github.com/repos/microsoft/vscode/releases{/id}',
  deployments_url: 'https://api.github.com/repos/microsoft/vscode/deployments',
  created_at: '2015-09-03T20:23:38Z',
  updated_at: '2021-11-10T23:24:02Z',
  pushed_at: '2021-11-10T23:35:54Z',
  git_url: 'git://github.com/microsoft/vscode.git',
  ssh_url: 'git@github.com:microsoft/vscode.git',
  clone_url: 'https://github.com/microsoft/vscode.git',
  svn_url: 'https://github.com/microsoft/vscode',
  homepage: 'https://code.visualstudio.com',
  size: 422471,
  stargazers_count: 123868,
  watchers_count: 123868,
  language: 'TypeScript',
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: false,
  forks_count: 20655,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 5155,
  license: Object,
  allow_forking: true,
  is_template: false,
  visibility: 'public',
  forks: 20655,
  open_issues: 5155,
  watchers: 123868,
  default_branch: 'main',
  score: 1
};
